let users = [{ "id": 1, "first_name": "Rikki", "last_name": "Choldcroft", "email": "rcholdcroft0@cafepress.com", "gender": "Male" },
{ "id": 2, "first_name": "Godwin", "last_name": "Portman", "email": "gportman1@digg.com", "gender": "Polygender" },
{ "id": 3, "first_name": "Tabatha", "last_name": "Steed", "email": "tsteed2@ehow.com", "gender": "Female" },
{ "id": 4, "first_name": "Frasco", "last_name": "Tomovic", "email": "ftomovic3@slashdot.org", "gender": "Male" },
{ "id": 5, "first_name": "Zaneta", "last_name": "Herety", "email": "zherety4@google.com.br", "gender": "Agender" },
{ "id": 6, "first_name": "Denny", "last_name": "Fewlass", "email": "dfewlass5@auda.org.au", "gender": "Female" },
{ "id": 7, "first_name": "Chet", "last_name": "Critchard", "email": "ccritchard6@imgur.com", "gender": "Male" },
{ "id": 8, "first_name": "Eachelle", "last_name": "Flaunders", "email": "eflaunders7@networksolutions.com", "gender": "Female" },
{ "id": 9, "first_name": "Hayyim", "last_name": "Viccars", "email": "hviccars8@baidu.com", "gender": "Male" },
{ "id": 10, "first_name": "Rosabella", "last_name": "Duxbury", "email": "rduxbury9@webmd.com", "gender": "Female" },
{ "id": 11, "first_name": "Jud", "last_name": "Simonyi", "email": "jsimonyia@stanford.edu", "gender": "Male" },
{ "id": 12, "first_name": "Josias", "last_name": "Durdy", "email": "jdurdyb@hhs.gov", "gender": "Genderfluid" },
{ "id": 13, "first_name": "Edsel", "last_name": "Robbel", "email": "erobbelc@bizjournals.com", "gender": "Male" },
{ "id": 14, "first_name": "Constantino", "last_name": "Persich", "email": "cpersichd@xinhuanet.com", "gender": "Male" },
{ "id": 15, "first_name": "Darbie", "last_name": "Seggie", "email": "dseggiee@usatoday.com", "gender": "Female" },
{ "id": 16, "first_name": "Ulberto", "last_name": "Futcher", "email": "ufutcherf@china.com.cn", "gender": "Bigender" },
{ "id": 17, "first_name": "Vinni", "last_name": "Sarge", "email": "vsargeg@delicious.com", "gender": "Female" },
{ "id": 18, "first_name": "Zolly", "last_name": "Cheetam", "email": "zcheetamh@ning.com", "gender": "Genderqueer" },
{ "id": 19, "first_name": "Elston", "last_name": "Hagwood", "email": "ehagwoodi@dell.com", "gender": "Male" },
{ "id": 20, "first_name": "Mychal", "last_name": "Dovey", "email": "mdoveyj@google.cn", "gender": "Male" },
{ "id": 21, "first_name": "Sabina", "last_name": "Ysson", "email": "syssonk@ibm.com", "gender": "Female" },
{ "id": 22, "first_name": "Sally", "last_name": "Duckinfield", "email": "sduckinfieldl@livejournal.com", "gender": "Polygender" },
{ "id": 23, "first_name": "Arte", "last_name": "Feore", "email": "afeorem@networkadvertising.org", "gender": "Bigender" },
{ "id": 24, "first_name": "Gerard", "last_name": "Morritt", "email": "gmorrittn@marriott.com", "gender": "Polygender" },
{ "id": 25, "first_name": "Gannie", "last_name": "Double", "email": "gdoubleo@sfgate.com", "gender": "Male" },
{ "id": 26, "first_name": "Dalton", "last_name": "Pimerick", "email": "dpimerickp@qq.com", "gender": "Genderfluid" },
{ "id": 27, "first_name": "Carmela", "last_name": "Koba", "email": "ckobaq@fastcompany.com", "gender": "Female" },
{ "id": 28, "first_name": "Vicky", "last_name": "Kesley", "email": "vkesleyr@google.com.hk", "gender": "Female" },
{ "id": 29, "first_name": "Linnet", "last_name": "McCobb", "email": "lmccobbs@addthis.com", "gender": "Female" },
{ "id": 30, "first_name": "Adela", "last_name": "Ivanishin", "email": "aivanishint@skype.com", "gender": "Female" },
{ "id": 31, "first_name": "Joye", "last_name": "Dodell", "email": "jdodellu@alibaba.com", "gender": "Female" },
{ "id": 32, "first_name": "Yorgo", "last_name": "Imason", "email": "yimasonv@shinystat.com", "gender": "Male" },
{ "id": 33, "first_name": "Guinevere", "last_name": "Rowlings", "email": "growlingsw@cbc.ca", "gender": "Female" },
{ "id": 34, "first_name": "Sally", "last_name": "Pedroli", "email": "spedrolix@blog.com", "gender": "Female" },
{ "id": 35, "first_name": "Maxwell", "last_name": "Neiland", "email": "mneilandy@ustream.tv", "gender": "Male" },
{ "id": 36, "first_name": "Virginie", "last_name": "Iggo", "email": "viggoz@symantec.com", "gender": "Female" },
{ "id": 37, "first_name": "Amory", "last_name": "Le Grand", "email": "alegrand10@ibm.com", "gender": "Male" },
{ "id": 38, "first_name": "Tamar", "last_name": "Sigward", "email": "tsigward11@hubpages.com", "gender": "Female" },
{ "id": 39, "first_name": "Jarrett", "last_name": "Giacobilio", "email": "jgiacobilio12@independent.co.uk", "gender": "Male" },
{ "id": 40, "first_name": "Rozanna", "last_name": "Kos", "email": "rkos13@google.co.jp", "gender": "Female" },
{ "id": 41, "first_name": "Juanita", "last_name": "MacMeanma", "email": "jmacmeanma14@wsj.com", "gender": "Female" },
{ "id": 42, "first_name": "Kinsley", "last_name": "Pearsey", "email": "kpearsey15@irs.gov", "gender": "Male" },
{ "id": 43, "first_name": "Brennan", "last_name": "Bote", "email": "bbote16@bravesites.com", "gender": "Male" },
{ "id": 44, "first_name": "Yanaton", "last_name": "Grieves", "email": "ygrieves17@mysql.com", "gender": "Male" },
{ "id": 45, "first_name": "Killian", "last_name": "Shortan", "email": "kshortan18@ocn.ne.jp", "gender": "Male" },
{ "id": 46, "first_name": "Devinne", "last_name": "Paye", "email": "dpaye19@forbes.com", "gender": "Female" },
{ "id": 47, "first_name": "Millisent", "last_name": "Moyes", "email": "mmoyes1a@bluehost.com", "gender": "Polygender" },
{ "id": 48, "first_name": "Georgeta", "last_name": "McKea", "email": "gmckea1b@histats.com", "gender": "Female" },
{ "id": 49, "first_name": "Anselma", "last_name": "Blakeley", "email": "ablakeley1c@drupal.org", "gender": "Female" },
{ "id": 50, "first_name": "Caresa", "last_name": "Cramp", "email": "ccramp1d@paypal.com", "gender": "Female" },
{ "id": 51, "first_name": "Stuart", "last_name": "Ferronier", "email": "sferronier1e@mail.ru", "gender": "Bigender" },
{ "id": 52, "first_name": "Ozzie", "last_name": "Holby", "email": "oholby1f@w3.org", "gender": "Male" },
{ "id": 53, "first_name": "August", "last_name": "Valentinuzzi", "email": "avalentinuzzi1g@tripadvisor.com", "gender": "Male" },
{ "id": 54, "first_name": "Kristian", "last_name": "Pauli", "email": "kpauli1h@chicagotribune.com", "gender": "Male" },
{ "id": 55, "first_name": "Charla", "last_name": "Handsheart", "email": "chandsheart1i@booking.com", "gender": "Polygender" },
{ "id": 56, "first_name": "Dickie", "last_name": "Trousdale", "email": "dtrousdale1j@soundcloud.com", "gender": "Male" },
{ "id": 57, "first_name": "Salmon", "last_name": "Polon", "email": "spolon1k@google.de", "gender": "Male" },
{ "id": 58, "first_name": "Maressa", "last_name": "Hunnable", "email": "mhunnable1l@ebay.co.uk", "gender": "Female" },
{ "id": 59, "first_name": "Sanders", "last_name": "Bruckner", "email": "sbruckner1m@constantcontact.com", "gender": "Male" },
{ "id": 60, "first_name": "Jeri", "last_name": "Le Brum", "email": "jlebrum1n@a8.net", "gender": "Female" },
{ "id": 61, "first_name": "Jesselyn", "last_name": "Fiddiman", "email": "jfiddiman1o@pbs.org", "gender": "Female" },
{ "id": 62, "first_name": "Debera", "last_name": "Mitchelhill", "email": "dmitchelhill1p@parallels.com", "gender": "Female" },
{ "id": 63, "first_name": "Norrie", "last_name": "Law", "email": "nlaw1q@msu.edu", "gender": "Female" },
{ "id": 64, "first_name": "Kathy", "last_name": "Mocquer", "email": "kmocquer1r@phpbb.com", "gender": "Female" },
{ "id": 65, "first_name": "Kylynn", "last_name": "Barrowcliff", "email": "kbarrowcliff1s@mapquest.com", "gender": "Female" },
{ "id": 66, "first_name": "Hal", "last_name": "Moynham", "email": "hmoynham1t@yellowbook.com", "gender": "Male" },
{ "id": 67, "first_name": "Rayshell", "last_name": "Wheildon", "email": "rwheildon1u@omniture.com", "gender": "Female" },
{ "id": 68, "first_name": "Irma", "last_name": "Gino", "email": "igino1v@yellowpages.com", "gender": "Female" },
{ "id": 69, "first_name": "Eachelle", "last_name": "Gerhold", "email": "egerhold1w@shutterfly.com", "gender": "Bigender" },
{ "id": 70, "first_name": "Laney", "last_name": "Bream", "email": "lbream1x@bbc.co.uk", "gender": "Female" },
{ "id": 71, "first_name": "Theodosia", "last_name": "Beedom", "email": "tbeedom1y@psu.edu", "gender": "Female" },
{ "id": 72, "first_name": "Rhona", "last_name": "Nattrass", "email": "rnattrass1z@imageshack.us", "gender": "Female" },
{ "id": 73, "first_name": "Lanny", "last_name": "Janning", "email": "ljanning20@taobao.com", "gender": "Female" },
{ "id": 74, "first_name": "Clayson", "last_name": "Wesgate", "email": "cwesgate21@nydailynews.com", "gender": "Male" },
{ "id": 75, "first_name": "Keary", "last_name": "Canter", "email": "kcanter22@washingtonpost.com", "gender": "Male" },
{ "id": 76, "first_name": "Jessie", "last_name": "Steffens", "email": "jsteffens23@discovery.com", "gender": "Female" },
{ "id": 77, "first_name": "Gabbie", "last_name": "Ayerst", "email": "gayerst24@weather.com", "gender": "Female" },
{ "id": 78, "first_name": "Karlotte", "last_name": "Shorthill", "email": "kshorthill25@usatoday.com", "gender": "Female" },
{ "id": 79, "first_name": "Matt", "last_name": "Spacey", "email": "mspacey26@indiatimes.com", "gender": "Male" },
{ "id": 80, "first_name": "Grissel", "last_name": "Gervaise", "email": "ggervaise27@sourceforge.net", "gender": "Female" },
{ "id": 81, "first_name": "Rochester", "last_name": "Tomasian", "email": "rtomasian28@dion.ne.jp", "gender": "Male" },
{ "id": 82, "first_name": "Vera", "last_name": "Zieme", "email": "vzieme29@ucoz.ru", "gender": "Female" },
{ "id": 83, "first_name": "Berti", "last_name": "Faivre", "email": "bfaivre2a@addtoany.com", "gender": "Polygender" },
{ "id": 84, "first_name": "Cynde", "last_name": "Mateus", "email": "cmateus2b@nifty.com", "gender": "Female" },
{ "id": 85, "first_name": "Crissy", "last_name": "Couroy", "email": "ccouroy2c@desdev.cn", "gender": "Female" },
{ "id": 86, "first_name": "Ellsworth", "last_name": "Bennison", "email": "ebennison2d@amazon.com", "gender": "Male" },
{ "id": 87, "first_name": "Bee", "last_name": "Aubury", "email": "baubury2e@vistaprint.com", "gender": "Female" },
{ "id": 88, "first_name": "Julita", "last_name": "Oneile", "email": "joneile2f@dailymotion.com", "gender": "Female" },
{ "id": 89, "first_name": "Anatollo", "last_name": "Rousel", "email": "arousel2g@php.net", "gender": "Genderfluid" },
{ "id": 90, "first_name": "Val", "last_name": "Luckin", "email": "vluckin2h@independent.co.uk", "gender": "Male" },
{ "id": 91, "first_name": "Onfroi", "last_name": "Bougen", "email": "obougen2i@umich.edu", "gender": "Male" },
{ "id": 92, "first_name": "Tobey", "last_name": "Bilson", "email": "tbilson2j@topsy.com", "gender": "Female" },
{ "id": 93, "first_name": "Colver", "last_name": "Rigmond", "email": "crigmond2k@ameblo.jp", "gender": "Male" },
{ "id": 94, "first_name": "Nicola", "last_name": "Mutch", "email": "nmutch2l@oakley.com", "gender": "Female" },
{ "id": 95, "first_name": "Stacey", "last_name": "Fellibrand", "email": "sfellibrand2m@gizmodo.com", "gender": "Female" },
{ "id": 96, "first_name": "Abigael", "last_name": "Hardesty", "email": "ahardesty2n@latimes.com", "gender": "Female" },
{ "id": 97, "first_name": "Calley", "last_name": "Pettiford", "email": "cpettiford2o@miibeian.gov.cn", "gender": "Female" },
{ "id": 98, "first_name": "Lyndsay", "last_name": "Purdom", "email": "lpurdom2p@jiathis.com", "gender": "Female" },
{ "id": 99, "first_name": "Liam", "last_name": "Delwater", "email": "ldelwater2q@patch.com", "gender": "Male" },
{ "id": 100, "first_name": "Ibby", "last_name": "Denizet", "email": "idenizet2r@instagram.com", "gender": "Female" }]


console.log(typeof users)
console.log(users.length)

let i = 0
while (i <= users.length - 1) {
    console.log(users[i].first_name)
    i++
}
/* for (user of users) {
    console.log(user.id)
} */
